spring:
  application:
    name: rich
    cnName: 发财致富

server:
  port: 9008
  context-path: /

connect:
  proxySwitch: true
  proxyIp: 10.22.98.21
  proxyPort: 8080

weapons:
  url: https://buff.163.com/api/market/goods?game=pubg&page_num=1&category_group=weapons&sort_by=price.desc&_=1523254920175,https://buff.163.com/api/market/goods?game=pubg&page_num=2&category_group=weapons&sort_by=price.desc&_=1523254920178

result:
  output: /home/jason/Desktop/rich/rich-

gifts:
  input: /home/jason/Desktop/rich/gift.json

#security:
#  user:
#    name: admin
#    password: admin

